### ISSUE TITLE
Merge conflict tags in python file

### ISSUE THREAD

**Issue by goatsweater** [canmet-energy/btap_ml#28]
There are markings from a git merge conflict left in the [`plot.py` file](https://github.com/canmet-energy/btap_ml/blob/95578d8a0febf609faed9250ce7479e7037be036/src/plot.py#L16). This results in a runtime error for invalid syntax.

```
(venv) jovyan@btap-reg-0:~/btap_ml/src$ python3 preprocessing.py --in_build_params input_data/output_2021-10-04.xlsx --in_hour input_data/total_hourly_res_2021-10-04.csv --in_weather weather/CAN_QC_Montreal-Trudeau.Intl.AP.716270_CWEC2016.epw.parquet --output_path output_data/preprocessing_out --in_build_params_val input_data/output.xlsx --in_hour_val input_data/total_hourly_res.csv
Traceback (most recent call last):
  File "preprocessing.py", line 26, in <module>
    import plot as pl
  File "/home/jovyan/btap_ml/src/plot.py", line 16
    <<<<<<< HEAD
    ^
SyntaxError: invalid syntax
```

**Comment by goatsweater** [comment]
Fixed by #29
