### ISSUE TITLE
Feature selection scalar and estimators missing

### ISSUE THREAD

**Issue by goatsweater** [canmet-energy/btap_ml#50]
It seems like scalars and estimators are not imported in `feature_selection.py`. Trying to run feature selection results in a crash:

```
Traceback (most recent call last):
  File "feature_selection.py", line 104, in <module>
    select_features(args)
  File "feature_selection.py", line 48, in select_features
    scalerx= RobustScaler()
NameError: name 'RobustScaler' is not defined
```

**Comment by goatsweater** [comment]
It looks like the imports do exist on the [container image used in the pipeline](https://github.com/StatCan/aaw-contrib-containers/blob/994b5355070db7d518aabe92788231c5075a7e2a/btap/src/feature_selection.py#L4).

The last time I was able to find the required imports in the history is at 9afde5e82bec3bf70b954d35b2072249f77dc2d0. Unclear if they can just be re-added.

**Comment by goatsweater** [comment]
The fix was applied in https://github.com/canmet-energy/btap_ml/commit/91a7355f9c74d58486d285c9b55340646b1179cd
